[package]
name = "librarian-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Used for global common SCSS
[build-dependencies]
grass = "0.12.2"


[dependencies]
common-local = { path = "../common", features = ["frontend"] }

common = { path = "../../global_common", features = ["frontend"] }

# reqwest = { version = "0.11", features = ["multipart"] }
tokio = { workspace = true, features = ["time"] }

serde = { workspace = true }
serde_urlencoded = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }

wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
gloo-utils = "0.1"
gloo-file = { version = "0.2", features = ["futures"] }
gloo-timers = "0.2"
js-sys = "0.3"

base64 = { workspace = true }
chrono = { workspace = true, features = ["wasmbind"] }
urlencoding = { workspace = true }
lazy_static = { workspace = true }
futures = "0.3"
reqwasm = "0.5"

anyhow = { workspace = true }
log = { workspace = true }

yew = "0.20"
yew-agent = "0.2"
yew-router = "0.17"
yew-hooks = "0.2"

wasm-logger = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
	"DomTokenList",
	"DomRect",
	"FormData",
	"Headers",
	"Request",
	"RequestInit",
	"RequestMode",
	"Response",
	"Window",
	"DataTransfer",
	"Document",
	"Element",
	"HtmlIFrameElement",
	"HtmlSelectElement",
	"CssStyleDeclaration",
	"Touch",
	"TouchEvent",
	"TouchList"
]